# Generated by Django 4.0.4 on 2022-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
