# Generated by Django 4.0.4 on 2022-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
